# Generated by Django 5.0.7 on 2024-07-31 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managment_System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('Hospital_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Managment_System.hospital')),
            ],
        ),
    ]
