# Generated by Django 5.0.7 on 2024-07-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Managment_System', '0003_remove_doctor_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Hospital_name',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_name',
            new_name='name',
        ),
    ]
